//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Cd40Cfg.proto
namespace U5ki.Infrastructure
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ParametrosGeneralesSistema")]
  public partial class ParametrosGeneralesSistema : global::ProtoBuf.IExtensible
  {
    public ParametrosGeneralesSistema() {}
    

    private uint _TiempoMaximoPTT = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"TiempoMaximoPTT", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint TiempoMaximoPTT
    {
      get { return _TiempoMaximoPTT; }
      set { _TiempoMaximoPTT = value; }
    }

    private uint _TiempoSinJack1 = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"TiempoSinJack1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint TiempoSinJack1
    {
      get { return _TiempoSinJack1; }
      set { _TiempoSinJack1 = value; }
    }

    private uint _TiempoSinJack2 = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"TiempoSinJack2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint TiempoSinJack2
    {
      get { return _TiempoSinJack2; }
      set { _TiempoSinJack2 = value; }
    }

    private uint _TamLiteralEnlExt = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"TamLiteralEnlExt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint TamLiteralEnlExt
    {
      get { return _TamLiteralEnlExt; }
      set { _TamLiteralEnlExt = value; }
    }

    private uint _TamLiteralEnlDA = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"TamLiteralEnlDA", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint TamLiteralEnlDA
    {
      get { return _TamLiteralEnlDA; }
      set { _TamLiteralEnlDA = value; }
    }

    private uint _TamLiteralEnlIA = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"TamLiteralEnlIA", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint TamLiteralEnlIA
    {
      get { return _TamLiteralEnlIA; }
      set { _TamLiteralEnlIA = value; }
    }

    private uint _TamLiteralEnlAG = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"TamLiteralEnlAG", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint TamLiteralEnlAG
    {
      get { return _TamLiteralEnlAG; }
      set { _TamLiteralEnlAG = value; }
    }

    private uint _TamLiteralEmplazamiento = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"TamLiteralEmplazamiento", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint TamLiteralEmplazamiento
    {
      get { return _TamLiteralEmplazamiento; }
      set { _TamLiteralEmplazamiento = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RangosSCV")]
  public partial class RangosSCV : global::ProtoBuf.IExtensible
  {
    public RangosSCV() {}
    

    private uint _IdPrefijo = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"IdPrefijo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint IdPrefijo
    {
      get { return _IdPrefijo; }
      set { _IdPrefijo = value; }
    }

    private string _IdAbonado = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"IdAbonado", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string IdAbonado
    {
      get { return _IdAbonado; }
      set { _IdAbonado = value; }
    }

    private ulong _Inicial = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Inicial", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Inicial
    {
      get { return _Inicial; }
      set { _Inicial = value; }
    }

    private ulong _Final = default(ulong);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Final", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Final
    {
      get { return _Final; }
      set { _Final = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlanRutas")]
  public partial class PlanRutas : global::ProtoBuf.IExtensible
  {
    public PlanRutas() {}
    

    private string _TipoRuta = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"TipoRuta", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string TipoRuta
    {
      get { return _TipoRuta; }
      set { _TipoRuta = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _ListaTroncales = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"ListaTroncales", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> ListaTroncales
    {
      get { return _ListaTroncales; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NumeracionATS")]
  public partial class NumeracionATS : global::ProtoBuf.IExtensible
  {
    public NumeracionATS() {}
    

    private bool _CentralPropia = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"CentralPropia", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool CentralPropia
    {
      get { return _CentralPropia; }
      set { _CentralPropia = value; }
    }

    private bool _Throwswitching = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Throwswitching", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool Throwswitching
    {
      get { return _Throwswitching; }
      set { _Throwswitching = value; }
    }
    private readonly global::System.Collections.Generic.List<U5ki.Infrastructure.RangosSCV> _RangosOperador = new global::System.Collections.Generic.List<U5ki.Infrastructure.RangosSCV>();
    [global::ProtoBuf.ProtoMember(3, Name=@"RangosOperador", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<U5ki.Infrastructure.RangosSCV> RangosOperador
    {
      get { return _RangosOperador; }
    }
  
    private readonly global::System.Collections.Generic.List<U5ki.Infrastructure.RangosSCV> _RangosPrivilegiados = new global::System.Collections.Generic.List<U5ki.Infrastructure.RangosSCV>();
    [global::ProtoBuf.ProtoMember(4, Name=@"RangosPrivilegiados", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<U5ki.Infrastructure.RangosSCV> RangosPrivilegiados
    {
      get { return _RangosPrivilegiados; }
    }
  
    private readonly global::System.Collections.Generic.List<U5ki.Infrastructure.PlanRutas> _ListaRutas = new global::System.Collections.Generic.List<U5ki.Infrastructure.PlanRutas>();
    [global::ProtoBuf.ProtoMember(5, Name=@"ListaRutas", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<U5ki.Infrastructure.PlanRutas> ListaRutas
    {
      get { return _ListaRutas; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DireccionamientoIP")]
  public partial class DireccionamientoIP : global::ProtoBuf.IExtensible
  {
    public DireccionamientoIP() {}
    

    private string _IdHost = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"IdHost", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string IdHost
    {
      get { return _IdHost; }
      set { _IdHost = value; }
    }

    private string _IpRed1 = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"IpRed1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string IpRed1
    {
      get { return _IpRed1; }
      set { _IpRed1 = value; }
    }

    private string _IpRed2 = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"IpRed2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string IpRed2
    {
      get { return _IpRed2; }
      set { _IpRed2 = value; }
    }

    private U5ki.Infrastructure.Tipo_Elemento_HW _TipoHost = U5ki.Infrastructure.Tipo_Elemento_HW.TEH_TOP;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"TipoHost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(U5ki.Infrastructure.Tipo_Elemento_HW.TEH_TOP)]
    public U5ki.Infrastructure.Tipo_Elemento_HW TipoHost
    {
      get { return _TipoHost; }
      set { _TipoHost = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlanRecursos")]
  public partial class PlanRecursos : global::ProtoBuf.IExtensible
  {
    public PlanRecursos() {}
    

    private string _IdRecurso = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"IdRecurso", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string IdRecurso
    {
      get { return _IdRecurso; }
      set { _IdRecurso = value; }
    }

    private U5ki.Infrastructure.TipoInterface _Tipo = U5ki.Infrastructure.TipoInterface.TI_Radio;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Tipo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(U5ki.Infrastructure.TipoInterface.TI_Radio)]
    public U5ki.Infrastructure.TipoInterface Tipo
    {
      get { return _Tipo; }
      set { _Tipo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ListaTroncales")]
  public partial class ListaTroncales : global::ProtoBuf.IExtensible
  {
    public ListaTroncales() {}
    

    private string _IdTroncal = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"IdTroncal", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string IdTroncal
    {
      get { return _IdTroncal; }
      set { _IdTroncal = value; }
    }

    private string _NumeroTest = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"NumeroTest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string NumeroTest
    {
      get { return _NumeroTest; }
      set { _NumeroTest = value; }
    }
    private readonly global::System.Collections.Generic.List<U5ki.Infrastructure.PlanRecursos> _ListaRecursos = new global::System.Collections.Generic.List<U5ki.Infrastructure.PlanRecursos>();
    [global::ProtoBuf.ProtoMember(3, Name=@"ListaRecursos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<U5ki.Infrastructure.PlanRecursos> ListaRecursos
    {
      get { return _ListaRecursos; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ListaRedes")]
  public partial class ListaRedes : global::ProtoBuf.IExtensible
  {
    public ListaRedes() {}
    

    private string _IdRed = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"IdRed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string IdRed
    {
      get { return _IdRed; }
      set { _IdRed = value; }
    }

    private uint _Prefijo = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Prefijo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Prefijo
    {
      get { return _Prefijo; }
      set { _Prefijo = value; }
    }
    private readonly global::System.Collections.Generic.List<U5ki.Infrastructure.PlanRecursos> _ListaRecursos = new global::System.Collections.Generic.List<U5ki.Infrastructure.PlanRecursos>();
    [global::ProtoBuf.ProtoMember(3, Name=@"ListaRecursos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<U5ki.Infrastructure.PlanRecursos> ListaRecursos
    {
      get { return _ListaRecursos; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AsignacionUsuariosTV")]
  public partial class AsignacionUsuariosTV : global::ProtoBuf.IExtensible
  {
    public AsignacionUsuariosTV() {}
    

    private string _IdUsuario = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"IdUsuario", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string IdUsuario
    {
      get { return _IdUsuario; }
      set { _IdUsuario = value; }
    }

    private string _IdHost = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"IdHost", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string IdHost
    {
      get { return _IdHost; }
      set { _IdHost = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AsignacionUsuariosDominantesTV")]
  public partial class AsignacionUsuariosDominantesTV : global::ProtoBuf.IExtensible
  {
    public AsignacionUsuariosDominantesTV() {}
    

    private string _IdUsuario = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"IdUsuario", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string IdUsuario
    {
      get { return _IdUsuario; }
      set { _IdUsuario = value; }
    }

    private string _IdHost = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"IdHost", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string IdHost
    {
      get { return _IdHost; }
      set { _IdHost = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AsignacionRecursosGW")]
  public partial class AsignacionRecursosGW : global::ProtoBuf.IExtensible
  {
    public AsignacionRecursosGW() {}
    

    private string _IdRecurso = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"IdRecurso", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string IdRecurso
    {
      get { return _IdRecurso; }
      set { _IdRecurso = value; }
    }

    private string _IdHost = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"IdHost", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string IdHost
    {
      get { return _IdHost; }
      set { _IdHost = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StrNumeroAbonado")]
  public partial class StrNumeroAbonado : global::ProtoBuf.IExtensible
  {
    public StrNumeroAbonado() {}
    

    private uint _Prefijo = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Prefijo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Prefijo
    {
      get { return _Prefijo; }
      set { _Prefijo = value; }
    }

    private string _NumeroAbonado = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"NumeroAbonado", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string NumeroAbonado
    {
      get { return _NumeroAbonado; }
      set { _NumeroAbonado = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DireccionamientoSIP")]
  public partial class DireccionamientoSIP : global::ProtoBuf.IExtensible
  {
    public DireccionamientoSIP() {}
    

    private string _IdUsuario = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"IdUsuario", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string IdUsuario
    {
      get { return _IdUsuario; }
      set { _IdUsuario = value; }
    }
    private readonly global::System.Collections.Generic.List<U5ki.Infrastructure.StrNumeroAbonado> _NumerosAbonadoQueAtiende = new global::System.Collections.Generic.List<U5ki.Infrastructure.StrNumeroAbonado>();
    [global::ProtoBuf.ProtoMember(2, Name=@"NumerosAbonadoQueAtiende", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<U5ki.Infrastructure.StrNumeroAbonado> NumerosAbonadoQueAtiende
    {
      get { return _NumerosAbonadoQueAtiende; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NumerosAbonado")]
  public partial class NumerosAbonado : global::ProtoBuf.IExtensible
  {
    public NumerosAbonado() {}
    

    private uint _Prefijo = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Prefijo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Prefijo
    {
      get { return _Prefijo; }
      set { _Prefijo = value; }
    }

    private string _Numero = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Numero", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Numero
    {
      get { return _Numero; }
      set { _Numero = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SectoresSCV")]
  public partial class SectoresSCV : global::ProtoBuf.IExtensible
  {
    public SectoresSCV() {}
    

    private string _IdParejaUCS = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"IdParejaUCS", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string IdParejaUCS
    {
      get { return _IdParejaUCS; }
      set { _IdParejaUCS = value; }
    }

    private string _TipoPosicion = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"TipoPosicion", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string TipoPosicion
    {
      get { return _TipoPosicion; }
      set { _TipoPosicion = value; }
    }

    private uint _PrioridadR2 = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"PrioridadR2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint PrioridadR2
    {
      get { return _PrioridadR2; }
      set { _PrioridadR2 = value; }
    }

    private uint _TipoHMI = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"TipoHMI", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint TipoHMI
    {
      get { return _TipoHMI; }
      set { _TipoHMI = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ParametrosSectorSCVKeepAlive")]
  public partial class ParametrosSectorSCVKeepAlive : global::ProtoBuf.IExtensible
  {
    public ParametrosSectorSCVKeepAlive() {}
    

    private uint _NumLlamadasEntrantesIda = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"NumLlamadasEntrantesIda", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint NumLlamadasEntrantesIda
    {
      get { return _NumLlamadasEntrantesIda; }
      set { _NumLlamadasEntrantesIda = value; }
    }

    private uint _NumLlamadasEnIda = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"NumLlamadasEnIda", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint NumLlamadasEnIda
    {
      get { return _NumLlamadasEnIda; }
      set { _NumLlamadasEnIda = value; }
    }

    private uint _NumFrecPagina = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"NumFrecPagina", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint NumFrecPagina
    {
      get { return _NumFrecPagina; }
      set { _NumFrecPagina = value; }
    }

    private uint _NumPagFrec = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"NumPagFrec", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint NumPagFrec
    {
      get { return _NumPagFrec; }
      set { _NumPagFrec = value; }
    }

    private uint _NumEnlacesInternosPag = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"NumEnlacesInternosPag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint NumEnlacesInternosPag
    {
      get { return _NumEnlacesInternosPag; }
      set { _NumEnlacesInternosPag = value; }
    }

    private uint _NumPagEnlacesInt = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"NumPagEnlacesInt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint NumPagEnlacesInt
    {
      get { return _NumPagEnlacesInt; }
      set { _NumPagEnlacesInt = value; }
    }

    private bool _Intrusion = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"Intrusion", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool Intrusion
    {
      get { return _Intrusion; }
      set { _Intrusion = value; }
    }

    private bool _Intruido = default(bool);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"Intruido", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool Intruido
    {
      get { return _Intruido; }
      set { _Intruido = value; }
    }

    private uint _KeepAlivePeriod = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"KeepAlivePeriod", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint KeepAlivePeriod
    {
      get { return _KeepAlivePeriod; }
      set { _KeepAlivePeriod = value; }
    }

    private uint _KeepAliveMultiplier = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"KeepAliveMultiplier", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint KeepAliveMultiplier
    {
      get { return _KeepAliveMultiplier; }
      set { _KeepAliveMultiplier = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PermisosRedesSCV")]
  public partial class PermisosRedesSCV : global::ProtoBuf.IExtensible
  {
    public PermisosRedesSCV() {}
    

    private string _IdRed = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"IdRed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string IdRed
    {
      get { return _IdRed; }
      set { _IdRed = value; }
    }

    private bool _Llamar = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Llamar", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool Llamar
    {
      get { return _Llamar; }
      set { _Llamar = value; }
    }

    private bool _Recibir = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Recibir", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool Recibir
    {
      get { return _Recibir; }
      set { _Recibir = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TeclasSectorSCV")]
  public partial class TeclasSectorSCV : global::ProtoBuf.IExtensible
  {
    public TeclasSectorSCV() {}
    

    private bool _TransConConsultaPrev = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"TransConConsultaPrev", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool TransConConsultaPrev
    {
      get { return _TransConConsultaPrev; }
      set { _TransConConsultaPrev = value; }
    }

    private bool _TransDirecta = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"TransDirecta", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool TransDirecta
    {
      get { return _TransDirecta; }
      set { _TransDirecta = value; }
    }

    private bool _Conferencia = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Conferencia", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool Conferencia
    {
      get { return _Conferencia; }
      set { _Conferencia = value; }
    }

    private bool _Escucha = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Escucha", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool Escucha
    {
      get { return _Escucha; }
      set { _Escucha = value; }
    }

    private bool _Retener = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Retener", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool Retener
    {
      get { return _Retener; }
      set { _Retener = value; }
    }

    private bool _Captura = default(bool);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"Captura", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool Captura
    {
      get { return _Captura; }
      set { _Captura = value; }
    }

    private bool _Redireccion = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"Redireccion", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool Redireccion
    {
      get { return _Redireccion; }
      set { _Redireccion = value; }
    }

    private bool _RepeticionUltLlamada = default(bool);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"RepeticionUltLlamada", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool RepeticionUltLlamada
    {
      get { return _RepeticionUltLlamada; }
      set { _RepeticionUltLlamada = value; }
    }

    private bool _RellamadaAut = default(bool);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"RellamadaAut", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool RellamadaAut
    {
      get { return _RellamadaAut; }
      set { _RellamadaAut = value; }
    }

    private bool _TeclaPrioridad = default(bool);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"TeclaPrioridad", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool TeclaPrioridad
    {
      get { return _TeclaPrioridad; }
      set { _TeclaPrioridad = value; }
    }

    private bool _Tecla55mas1 = default(bool);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"Tecla55mas1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool Tecla55mas1
    {
      get { return _Tecla55mas1; }
      set { _Tecla55mas1 = value; }
    }

    private bool _Monitoring = default(bool);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"Monitoring", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool Monitoring
    {
      get { return _Monitoring; }
      set { _Monitoring = value; }
    }

    private bool _CoordinadorTF = default(bool);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"CoordinadorTF", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool CoordinadorTF
    {
      get { return _CoordinadorTF; }
      set { _CoordinadorTF = value; }
    }

    private bool _CoordinadorRD = default(bool);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"CoordinadorRD", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool CoordinadorRD
    {
      get { return _CoordinadorRD; }
      set { _CoordinadorRD = value; }
    }

    private bool _IntegracionRDTF = default(bool);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"IntegracionRDTF", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool IntegracionRDTF
    {
      get { return _IntegracionRDTF; }
      set { _IntegracionRDTF = value; }
    }

    private bool _LlamadaSelectiva = default(bool);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"LlamadaSelectiva", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool LlamadaSelectiva
    {
      get { return _LlamadaSelectiva; }
      set { _LlamadaSelectiva = value; }
    }

    private bool _GrupoBSS = default(bool);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"GrupoBSS", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool GrupoBSS
    {
      get { return _GrupoBSS; }
      set { _GrupoBSS = value; }
    }

    private bool _LTT = default(bool);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"LTT", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool LTT
    {
      get { return _LTT; }
      set { _LTT = value; }
    }

    private bool _SayAgain = default(bool);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"SayAgain", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool SayAgain
    {
      get { return _SayAgain; }
      set { _SayAgain = value; }
    }

    private bool _InhabilitacionRedirec = default(bool);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"InhabilitacionRedirec", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool InhabilitacionRedirec
    {
      get { return _InhabilitacionRedirec; }
      set { _InhabilitacionRedirec = value; }
    }

	private bool _Glp = default(bool);
	[global::ProtoBuf.ProtoMember(21, IsRequired = false, Name = @"Glp", DataFormat = global::ProtoBuf.DataFormat.Default)]
	[global::System.ComponentModel.DefaultValue(default(bool))]
	public bool Glp
	{
		get { return _Glp; }
		set { _Glp = value; }
	}

	private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NivelesSCV")]
  public partial class NivelesSCV : global::ProtoBuf.IExtensible
  {
    public NivelesSCV() {}
    

    private uint _CICL = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"CICL", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint CICL
    {
      get { return _CICL; }
      set { _CICL = value; }
    }

    private uint _CIPL = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"CIPL", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint CIPL
    {
      get { return _CIPL; }
      set { _CIPL = value; }
    }

    private uint _CPICL = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"CPICL", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint CPICL
    {
      get { return _CPICL; }
      set { _CPICL = value; }
    }

    private uint _CPIPL = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"CPIPL", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint CPIPL
    {
      get { return _CPIPL; }
      set { _CPIPL = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CfgUsuario")]
  public partial class CfgUsuario : global::ProtoBuf.IExtensible
  {
    public CfgUsuario() {}
    

    private string _Nombre = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Nombre", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Nombre
    {
      get { return _Nombre; }
      set { _Nombre = value; }
    }

    private string _IdIdentificador = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"IdIdentificador", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string IdIdentificador
    {
      get { return _IdIdentificador; }
      set { _IdIdentificador = value; }
    }
    private readonly global::System.Collections.Generic.List<U5ki.Infrastructure.NumerosAbonado> _ListaAbonados = new global::System.Collections.Generic.List<U5ki.Infrastructure.NumerosAbonado>();
    [global::ProtoBuf.ProtoMember(3, Name=@"ListaAbonados", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<U5ki.Infrastructure.NumerosAbonado> ListaAbonados
    {
      get { return _ListaAbonados; }
    }
  

    private int _NumeroEnlacesInternos = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"NumeroEnlacesInternos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int NumeroEnlacesInternos
    {
      get { return _NumeroEnlacesInternos; }
      set { _NumeroEnlacesInternos = value; }
    }

    private int _NumeroEnlacesExternos = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"NumeroEnlacesExternos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int NumeroEnlacesExternos
    {
      get { return _NumeroEnlacesExternos; }
      set { _NumeroEnlacesExternos = value; }
    }

    private U5ki.Infrastructure.SectoresSCV _Sector = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"Sector", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public U5ki.Infrastructure.SectoresSCV Sector
    {
      get { return _Sector; }
      set { _Sector = value; }
    }

    private U5ki.Infrastructure.ParametrosSectorSCVKeepAlive _ParametrosDelSector = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"ParametrosDelSector", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public U5ki.Infrastructure.ParametrosSectorSCVKeepAlive ParametrosDelSector
    {
      get { return _ParametrosDelSector; }
      set { _ParametrosDelSector = value; }
    }
    private readonly global::System.Collections.Generic.List<U5ki.Infrastructure.PermisosRedesSCV> _PermisosRedDelSector = new global::System.Collections.Generic.List<U5ki.Infrastructure.PermisosRedesSCV>();
    [global::ProtoBuf.ProtoMember(8, Name=@"PermisosRedDelSector", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<U5ki.Infrastructure.PermisosRedesSCV> PermisosRedDelSector
    {
      get { return _PermisosRedDelSector; }
    }
  

    private U5ki.Infrastructure.TeclasSectorSCV _TeclasDelSector = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"TeclasDelSector", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public U5ki.Infrastructure.TeclasSectorSCV TeclasDelSector
    {
      get { return _TeclasDelSector; }
      set { _TeclasDelSector = value; }
    }

    private U5ki.Infrastructure.NivelesSCV _NivelesDelSector = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"NivelesDelSector", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public U5ki.Infrastructure.NivelesSCV NivelesDelSector
    {
      get { return _NivelesDelSector; }
      set { _NivelesDelSector = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CfgRecursoEnlaceExterno")]
  public partial class CfgRecursoEnlaceExterno : global::ProtoBuf.IExtensible
  {
    public CfgRecursoEnlaceExterno() {}
    

    private string _IdRecurso = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"IdRecurso", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string IdRecurso
    {
      get { return _IdRecurso; }
      set { _IdRecurso = value; }
    }

    private uint _Tipo = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Tipo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Tipo
    {
      get { return _Tipo; }
      set { _Tipo = value; }
    }

    private string _Estado = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Estado", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Estado
    {
      get { return _Estado; }
      set { _Estado = value; }
    }

    private uint _ModoConfPTT = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"ModoConfPTT", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint ModoConfPTT
    {
      get { return _ModoConfPTT; }
      set { _ModoConfPTT = value; }
    }

    private uint _NumFlujosAudio = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"NumFlujosAudio", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint NumFlujosAudio
    {
      get { return _NumFlujosAudio; }
      set { _NumFlujosAudio = value; }
    }

    private string _IdEmplazamiento = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"IdEmplazamiento", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string IdEmplazamiento
    {
      get { return _IdEmplazamiento; }
      set { _IdEmplazamiento = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CfgEnlaceExterno")]
  public partial class CfgEnlaceExterno : global::ProtoBuf.IExtensible
  {
    public CfgEnlaceExterno() {}
    

    private string _Literal = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Literal", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Literal
    {
      get { return _Literal; }
      set { _Literal = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _ListaPosicionesEnHmi = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"ListaPosicionesEnHmi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> ListaPosicionesEnHmi
    {
      get { return _ListaPosicionesEnHmi; }
    }
  

    private uint _TipoFrecuencia = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"TipoFrecuencia", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint TipoFrecuencia
    {
      get { return _TipoFrecuencia; }
      set { _TipoFrecuencia = value; }
    }

    private bool _ExclusividadTxRx = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"ExclusividadTxRx", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool ExclusividadTxRx
    {
      get { return _ExclusividadTxRx; }
      set { _ExclusividadTxRx = value; }
    }
    private readonly global::System.Collections.Generic.List<U5ki.Infrastructure.CfgRecursoEnlaceExterno> _ListaRecursos = new global::System.Collections.Generic.List<U5ki.Infrastructure.CfgRecursoEnlaceExterno>();
    [global::ProtoBuf.ProtoMember(5, Name=@"ListaRecursos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<U5ki.Infrastructure.CfgRecursoEnlaceExterno> ListaRecursos
    {
      get { return _ListaRecursos; }
    }
  

    private string _EstadoAsignacion = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"EstadoAsignacion", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string EstadoAsignacion
    {
      get { return _EstadoAsignacion; }
      set { _EstadoAsignacion = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _DestinoAudio = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(7, Name=@"DestinoAudio", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> DestinoAudio
    {
      get { return _DestinoAudio; }
    }
  

    private uint _Prioridad = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"Prioridad", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Prioridad
    {
      get { return _Prioridad; }
      set { _Prioridad = value; }
    }

    private bool _SupervisionPortadora = default(bool);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"SupervisionPortadora", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool SupervisionPortadora
    {
      get { return _SupervisionPortadora; }
      set { _SupervisionPortadora = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CfgRecursoEnlaceInterno")]
  public partial class CfgRecursoEnlaceInterno : global::ProtoBuf.IExtensible
  {
    public CfgRecursoEnlaceInterno() {}
    

    private uint _Prefijo = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Prefijo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Prefijo
    {
      get { return _Prefijo; }
      set { _Prefijo = value; }
    }

    private string _NombreRecurso = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"NombreRecurso", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string NombreRecurso
    {
      get { return _NombreRecurso; }
      set { _NombreRecurso = value; }
    }

    private string _NumeroAbonado = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"NumeroAbonado", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string NumeroAbonado
    {
      get { return _NumeroAbonado; }
      set { _NumeroAbonado = value; }
    }

    private U5ki.Infrastructure.TipoInterface _Interface = U5ki.Infrastructure.TipoInterface.TI_Radio;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Interface", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(U5ki.Infrastructure.TipoInterface.TI_Radio)]
    public U5ki.Infrastructure.TipoInterface Interface
    {
      get { return _Interface; }
      set { _Interface = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CfgEnlaceInterno")]
  public partial class CfgEnlaceInterno : global::ProtoBuf.IExtensible
  {
    public CfgEnlaceInterno() {}
    

    private string _Literal = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Literal", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Literal
    {
      get { return _Literal; }
      set { _Literal = value; }
    }

    private uint _PosicionHMI = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"PosicionHMI", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint PosicionHMI
    {
      get { return _PosicionHMI; }
      set { _PosicionHMI = value; }
    }

    private string _TipoEnlaceInterno = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"TipoEnlaceInterno", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string TipoEnlaceInterno
    {
      get { return _TipoEnlaceInterno; }
      set { _TipoEnlaceInterno = value; }
    }
    private readonly global::System.Collections.Generic.List<U5ki.Infrastructure.CfgRecursoEnlaceInterno> _ListaRecursos = new global::System.Collections.Generic.List<U5ki.Infrastructure.CfgRecursoEnlaceInterno>();
    [global::ProtoBuf.ProtoMember(4, Name=@"ListaRecursos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<U5ki.Infrastructure.CfgRecursoEnlaceInterno> ListaRecursos
    {
      get { return _ListaRecursos; }
    }
  

    private string _Dependencia = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Dependencia", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Dependencia
    {
      get { return _Dependencia; }
      set { _Dependencia = value; }
    }

    private uint _Prioridad = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"Prioridad", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Prioridad
    {
      get { return _Prioridad; }
      set { _Prioridad = value; }
    }

    private string _OrigenR2 = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"OrigenR2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string OrigenR2
    {
      get { return _OrigenR2; }
      set { _OrigenR2 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ConfiguracionSistema")]
  public partial class ConfiguracionSistema : global::ProtoBuf.IExtensible
  {
    public ConfiguracionSistema() {}
    

    private U5ki.Infrastructure.ParametrosGeneralesSistema _ParametrosGenerales = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ParametrosGenerales", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public U5ki.Infrastructure.ParametrosGeneralesSistema ParametrosGenerales
    {
      get { return _ParametrosGenerales; }
      set { _ParametrosGenerales = value; }
    }
    private readonly global::System.Collections.Generic.List<U5ki.Infrastructure.NumeracionATS> _PlanNumeracionATS = new global::System.Collections.Generic.List<U5ki.Infrastructure.NumeracionATS>();
    [global::ProtoBuf.ProtoMember(2, Name=@"PlanNumeracionATS", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<U5ki.Infrastructure.NumeracionATS> PlanNumeracionATS
    {
      get { return _PlanNumeracionATS; }
    }
  
    private readonly global::System.Collections.Generic.List<U5ki.Infrastructure.DireccionamientoIP> _PlanDireccionamientoIP = new global::System.Collections.Generic.List<U5ki.Infrastructure.DireccionamientoIP>();
    [global::ProtoBuf.ProtoMember(3, Name=@"PlanDireccionamientoIP", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<U5ki.Infrastructure.DireccionamientoIP> PlanDireccionamientoIP
    {
      get { return _PlanDireccionamientoIP; }
    }
  
    private readonly global::System.Collections.Generic.List<U5ki.Infrastructure.ListaTroncales> _PlanTroncales = new global::System.Collections.Generic.List<U5ki.Infrastructure.ListaTroncales>();
    [global::ProtoBuf.ProtoMember(4, Name=@"PlanTroncales", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<U5ki.Infrastructure.ListaTroncales> PlanTroncales
    {
      get { return _PlanTroncales; }
    }
  
    private readonly global::System.Collections.Generic.List<U5ki.Infrastructure.ListaRedes> _PlanRedes = new global::System.Collections.Generic.List<U5ki.Infrastructure.ListaRedes>();
    [global::ProtoBuf.ProtoMember(5, Name=@"PlanRedes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<U5ki.Infrastructure.ListaRedes> PlanRedes
    {
      get { return _PlanRedes; }
    }
  
    private readonly global::System.Collections.Generic.List<U5ki.Infrastructure.AsignacionUsuariosTV> _PlanAsignacionUsuarios = new global::System.Collections.Generic.List<U5ki.Infrastructure.AsignacionUsuariosTV>();
    [global::ProtoBuf.ProtoMember(6, Name=@"PlanAsignacionUsuarios", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<U5ki.Infrastructure.AsignacionUsuariosTV> PlanAsignacionUsuarios
    {
      get { return _PlanAsignacionUsuarios; }
    }
  
    private readonly global::System.Collections.Generic.List<U5ki.Infrastructure.AsignacionUsuariosDominantesTV> _PlanAsignacionUsuariosDominantes = new global::System.Collections.Generic.List<U5ki.Infrastructure.AsignacionUsuariosDominantesTV>();
    [global::ProtoBuf.ProtoMember(7, Name=@"PlanAsignacionUsuariosDominantes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<U5ki.Infrastructure.AsignacionUsuariosDominantesTV> PlanAsignacionUsuariosDominantes
    {
      get { return _PlanAsignacionUsuariosDominantes; }
    }
  
    private readonly global::System.Collections.Generic.List<U5ki.Infrastructure.AsignacionRecursosGW> _PlanAsignacionRecursos = new global::System.Collections.Generic.List<U5ki.Infrastructure.AsignacionRecursosGW>();
    [global::ProtoBuf.ProtoMember(8, Name=@"PlanAsignacionRecursos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<U5ki.Infrastructure.AsignacionRecursosGW> PlanAsignacionRecursos
    {
      get { return _PlanAsignacionRecursos; }
    }
  
    private readonly global::System.Collections.Generic.List<U5ki.Infrastructure.DireccionamientoSIP> _PlanDireccionamientoSIP = new global::System.Collections.Generic.List<U5ki.Infrastructure.DireccionamientoSIP>();
    [global::ProtoBuf.ProtoMember(9, Name=@"PlanDireccionamientoSIP", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<U5ki.Infrastructure.DireccionamientoSIP> PlanDireccionamientoSIP
    {
      get { return _PlanDireccionamientoSIP; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ConfiguracionUsuario")]
  public partial class ConfiguracionUsuario : global::ProtoBuf.IExtensible
  {
    public ConfiguracionUsuario() {}
    

    private U5ki.Infrastructure.CfgUsuario _User = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"User", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public U5ki.Infrastructure.CfgUsuario User
    {
      get { return _User; }
      set { _User = value; }
    }
    private readonly global::System.Collections.Generic.List<U5ki.Infrastructure.CfgEnlaceExterno> _RdLinks = new global::System.Collections.Generic.List<U5ki.Infrastructure.CfgEnlaceExterno>();
    [global::ProtoBuf.ProtoMember(2, Name=@"RdLinks", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<U5ki.Infrastructure.CfgEnlaceExterno> RdLinks
    {
      get { return _RdLinks; }
    }
  
    private readonly global::System.Collections.Generic.List<U5ki.Infrastructure.CfgEnlaceInterno> _TlfMhpLinks = new global::System.Collections.Generic.List<U5ki.Infrastructure.CfgEnlaceInterno>();
    [global::ProtoBuf.ProtoMember(3, Name=@"TlfLinks", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<U5ki.Infrastructure.CfgEnlaceInterno> TlfLinks
    {
      get { return _TlfMhpLinks; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Cd40Cfg")]
  public partial class Cd40Cfg : global::ProtoBuf.IExtensible
  {
    public Cd40Cfg() {}
    

    private string _Version = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Version
    {
      get { return _Version; }
      set { _Version = value; }
    }

    private U5ki.Infrastructure.ConfiguracionSistema _ConfiguracionGeneral = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ConfiguracionGeneral", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public U5ki.Infrastructure.ConfiguracionSistema ConfiguracionGeneral
    {
      get { return _ConfiguracionGeneral; }
      set { _ConfiguracionGeneral = value; }
    }
    private readonly global::System.Collections.Generic.List<U5ki.Infrastructure.ConfiguracionUsuario> _ConfiguracionUsuarios = new global::System.Collections.Generic.List<U5ki.Infrastructure.ConfiguracionUsuario>();
    [global::ProtoBuf.ProtoMember(3, Name=@"ConfiguracionUsuarios", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<U5ki.Infrastructure.ConfiguracionUsuario> ConfiguracionUsuarios
    {
      get { return _ConfiguracionUsuarios; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"Tipo_Elemento_HW")]
    public enum Tipo_Elemento_HW
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TEH_TOP", Value=0)]
      TEH_TOP = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TEH_TIFX", Value=1)]
      TEH_TIFX = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TEH_EXTERNO_RADIO", Value=2)]
      TEH_EXTERNO_RADIO = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TEH_EXTERNO_TELEFONIA", Value=3)]
      TEH_EXTERNO_TELEFONIA = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TEH_SISTEMA", Value=4)]
      TEH_SISTEMA = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"TipoInterface")]
    public enum TipoInterface
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TI_Radio", Value=0)]
      TI_Radio = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TI_LCEN", Value=1)]
      TI_LCEN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TI_BC", Value=2)]
      TI_BC = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TI_BL", Value=3)]
      TI_BL = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TI_AB", Value=4)]
      TI_AB = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TI_ATS_R2", Value=5)]
      TI_ATS_R2 = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TI_ATS_N5", Value=6)]
      TI_ATS_N5 = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TI_ATS_QSIG", Value=7)]
      TI_ATS_QSIG = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TI_ISDN_2BD", Value=8)]
      TI_ISDN_2BD = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TI_ISDN_30BD", Value=9)]
      TI_ISDN_30BD = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TI_I_O", Value=10)]
      TI_I_O = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TI_DATOS", Value=11)]
      TI_DATOS = 11,

        
      [global::ProtoBuf.ProtoEnum(Name=@"TI_RRC", Value=12)]
      TI_RRC = 12,

        
      [global::ProtoBuf.ProtoEnum(Name=@"TI_EyM_PP", Value=13)]
      TI_EyM_PP = 13,

        
      [global::ProtoBuf.ProtoEnum(Name=@"TI_EyM_MARC", Value=14)]
      TI_EyM_MARC = 14
    }
  
}